# Generated by Django 5.0.7 on 2024-08-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['doctor', 'patient'], name='reports_rep_doctor__daa1b4_idx'),
        ),
    ]
