# Generated by Django 5.0.7 on 2024-08-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('reports', '0002_report_reports_rep_doctor__daa1b4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient'),
        ),
    ]
