# Generated by Django 5.0.7 on 2024-08-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_doctor_alter_report_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
