# Generated by Django 5.0.7 on 2024-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(editable=False, max_length=240),
        ),
        migrations.AlterField(
            model_name='report',
            name='suggestion',
            field=models.TextField(blank=True, null=True, verbose_name='Suggestion'),
        ),
    ]
