# Generated by Django 5.0.7 on 2024-08-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('des', models.CharField(max_length=200, verbose_name='Description')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Practicing Doctors')),
                ('patients', models.ManyToManyField(to='patients.patient', verbose_name='Counsulting Patients')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specialization',
            },
        ),
    ]
