# Generated by Django 5.0.7 on 2024-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0003_alter_specialization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='slug',
            field=models.SlugField(editable=False, max_length=240),
        ),
    ]
