# Generated by Django 5.0.7 on 2024-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
