# Generated by Django 5.0.7 on 2024-08-01 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmc_id', models.IntegerField(unique=True, verbose_name='NMC ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('registration_year', models.DateField(verbose_name='Date of NMC registraion')),
                ('phone_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Enter the correct phone number', regex='(?:\\+?91[-\\s]?)?0?\\d{10}')], verbose_name='Phone number')),
                ('password', models.CharField(verbose_name='Password')),
                ('valid', models.BooleanField(default=False, verbose_name='Valid')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
